import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface WalletAuthRequest {
  publicKey: string;
}

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { publicKey }: WalletAuthRequest = await req.json();

    if (!publicKey) {
      return new Response(
        JSON.stringify({ error: "Public key is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize Supabase admin client
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check if wallet exists in BCC database (was generated by us)
    const { data: wallet, error: walletError } = await supabase
      .from("wallets")
      .select("id, email, public_key, confirmed")
      .eq("public_key", publicKey)
      .maybeSingle();

    if (walletError) {
      console.error("Error checking wallet:", walletError);
      return new Response(
        JSON.stringify({ error: "Failed to verify wallet" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Wallet not found - not a BCC wallet
    if (!wallet) {
      return new Response(
        JSON.stringify({
          isBccWallet: false,
          hasBccAccount: false,
          message: "This wallet was not generated by BCC.cash",
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if user has a BCC email account
    const { data: bccAccount, error: bccError } = await supabase
      .from("bcc_accounts")
      .select("id, bcc_username, forward_to_email, is_active")
      .eq("wallet_id", wallet.id)
      .maybeSingle();

    if (bccError) {
      console.error("Error checking BCC account:", bccError);
      return new Response(
        JSON.stringify({ error: "Failed to check BCC account" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Return wallet status
    return new Response(
      JSON.stringify({
        isBccWallet: true,
        hasBccAccount: !!bccAccount,
        bccEmail: bccAccount ? `${bccAccount.bcc_username}@bcc.cash` : null,
        walletId: wallet.id,
        originalEmail: wallet.email,
        isActive: bccAccount?.is_active ?? false,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in wallet-auth:", error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
