import { useWallet } from "@solana/wallet-adapter-react";
import { useWalletModal } from "@solana/wallet-adapter-react-ui";
import { Button } from "@/components/ui/button";
import { Wallet, LogOut, Mail, Loader2 } from "lucide-react";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { getBackendClient } from "@/lib/backendClient";
import { toast } from "sonner";

interface WalletStatus {
  isBccWallet: boolean;
  hasBccAccount: boolean;
  bccEmail?: string;
  walletId?: string;
  originalEmail?: string;
}

export const WalletConnectButton = () => {
  const { publicKey, connected, disconnect, connecting } = useWallet();
  const { setVisible } = useWalletModal();
  const navigate = useNavigate();
  const [walletStatus, setWalletStatus] = useState<WalletStatus | null>(null);
  const [isChecking, setIsChecking] = useState(false);

  // Check wallet status when connected
  useEffect(() => {
    const checkWalletStatus = async () => {
      if (!publicKey) {
        setWalletStatus(null);
        return;
      }

      setIsChecking(true);
      try {
        const supabase = getBackendClient();
        const { data, error } = await supabase.functions.invoke("wallet-auth", {
          body: { publicKey: publicKey.toBase58() },
        });

        if (error) {
          console.error("Error checking wallet:", error);
          toast.error("Failed to verify wallet");
          return;
        }

        setWalletStatus(data);

        if (!data.isBccWallet) {
          toast.error("This wallet was not generated by BCC.cash");
        } else if (data.hasBccAccount) {
          toast.success(`Welcome back! Your BCC email: ${data.bccEmail}`);
        } else {
          toast.success("Wallet verified! You can now claim your @bcc.cash email");
        }
      } catch (err) {
        console.error("Error:", err);
        toast.error("Failed to verify wallet");
      } finally {
        setIsChecking(false);
      }
    };

    if (connected && publicKey) {
      checkWalletStatus();
    }
  }, [connected, publicKey]);

  const handleConnect = () => {
    setVisible(true);
  };

  const handleDisconnect = () => {
    disconnect();
    setWalletStatus(null);
    toast.info("Wallet disconnected");
  };

  const handleGoToInbox = () => {
    navigate("/inbox");
  };

  const truncateAddress = (address: string) => {
    return `${address.slice(0, 4)}...${address.slice(-4)}`;
  };

  if (connecting || isChecking) {
    return (
      <Button variant="outline" size="sm" disabled className="gap-2">
        <Loader2 className="h-4 w-4 animate-spin" />
        <span className="hidden sm:inline">Connecting...</span>
      </Button>
    );
  }

  if (connected && publicKey) {
    return (
      <div className="flex items-center gap-2">
        {walletStatus?.isBccWallet && (
          <Button
            variant="gradient"
            size="sm"
            onClick={handleGoToInbox}
            className="gap-2"
          >
            <Mail className="h-4 w-4" />
            <span className="hidden sm:inline">
              {walletStatus.hasBccAccount ? "Inbox" : "Claim Email"}
            </span>
          </Button>
        )}
        <Button
          variant="outline"
          size="sm"
          onClick={handleDisconnect}
          className="gap-2"
        >
          <Wallet className="h-4 w-4" />
          <span className="hidden sm:inline">{truncateAddress(publicKey.toBase58())}</span>
          <LogOut className="h-4 w-4" />
        </Button>
      </div>
    );
  }

  return (
    <Button variant="gradient" size="sm" onClick={handleConnect} className="gap-2">
      <Wallet className="h-4 w-4" />
      <span className="hidden sm:inline">Connect Wallet</span>
    </Button>
  );
};
